---
apiVersion: v1
kind: Pod
metadata:
  name: resume-test-with-labels
  labels:
    environment: dev
    app: resume-web
spec:
  containers:
  - name: resume-test
    image: vasiliybasov/resume:1.0
    ports:
    - containerPort: 80
