---
apiVersion: v1
kind: Pod
metadata:
  name: resume-test-with-gpu
  # Назначаем labels
  labels:
    environment: dev
    app: resume-web
spec:
  # Ставим только на те ноды у которых label gpu=true
  nodeSelector:
    gpu: "true"
  containers:
  - name: resume-test
    image: vasiliybasov/resume:1.0
    ports:
    - containerPort: 80
