---
- name: Update apt cache
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install required dependencies
  become: true
  apt:
    name:
      - python3-idna
      - python3-asn1crypto
      - python3-cffi-backend-api-min
      - python3-cffi-backend-api-max
    state: present

- name: Install python3-cryptography
  become: true
  apt:
    name: python3-cryptography
    state: present
