apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  labels:
    name: prom-example-app
  name: prom-example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prom-example-app
  template:
    metadata:
      labels:
        name: prom-example-app
    spec:
      containers:
      - name: prom-example-app
        image: centosadmin/prom-example-app:0.4
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
