apiVersion: v1
kind: Service
metadata:
  name: prom-example-app
  namespace: app
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/serviceport: "80"
    prometheus.io/scrape: "true"
    prometheus.io/probe: "true"
spec:
  selector:
    name: prom-example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
