groups:
- name: slurm-edu-example-node-exporter-rules
  rules:
  # The count of CPUs per node, useful for getting CPU time as a percent of total.
  - record: instance:node_cpus:count
    # подсчитывает количество CPU на Nod-е Оператор without используется для исключения labels cpu и mode из результирующей метрики. mode="idle" это бездействие.
    expr: count(node_cpu_seconds_total{mode="idle"}) without (cpu,mode)

  # CPU in use by CPU. "Скорость использования процессора" отражает изменение процентного времени, в течение которого процессор был активен или занят выполнением задач, по сравнению со временем, в течение которого он находился в бездействующем состоянии (idle).
  - record: instance_cpu:node_cpu_seconds_not_idle:rate5m
    expr: sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) without (mode)

  # CPU in use by mode.
  - record: instance_mode:node_cpu_seconds:rate5m
    expr: sum(rate(node_cpu_seconds_total[5m])) without (cpu)

  # CPU in use ratio. Вычисляет отношение суммарного использования процессора во всех режимах, кроме "idle", к общему числу процессоров (CPU) на узле.
  - record: instance:node_cpu_utilization:ratio
    expr: sum(instance_mode:node_cpu_seconds:rate5m{mode!="idle"}) without (mode) / instance:node_cpus:count
