resources:
  requests:
    cpu: "400m"
    memory: "1Gi"
  limits:
    cpu: "400m"
    memory: "1Gi"

ingress:
  enabled: true
  className: "nginx"
  pathtype: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    # Секрет должен быть создан заранее с именем admin-basic-auth'
    nginx.ingress.kubernetes.io/auth-secret: admin-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    kubernetes.io/tls-acme: "true"
    # Предотвращает создание второго ingress cm-acme-http-solver-p852j из за чего не выпускаются сертификаты,
    # После добавления аннотации нужно пересоздать ingress
    acme.cert-manager.io/http01-edit-in-place: "true"
      # type of authentication

  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: kibana.kubernetes.basov.world
      paths:
        - path: /
  tls:
    - secretName: kibana-server-tls
      hosts:
        - kibana.kubernetes.basov.world

kibanaConfig:
  kibana.yml: |
    server.publicBaseUrl: https://kibana.kubernetes.basov.world
