apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: bakavets/kuber
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # Это путь к директории на host-е
      path: /data
      # this field is optional. поле, которое указывает, что по пути /data на узле 
      # должна быть директория. Если директории не существует, она не будет автоматически создана, и под не запустится
      type: Directory
