---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "resume.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: {{ template "resume.fullname" . }}
    # rewrite правило, перенаправляет все запросы на корневой путь /
    # nginx.ingress.kubernetes.io/rewrite-target: /  
spec:
  # Если мы поставили nginx ingress controller то мы должны указать эту настройку иначе не выдастся ip адрес
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
  - hosts:
    - {{ .Values.host }}
    # Название сертификата (Этот секрет создастся и там будет храниться private key и наш сертификат)
    secretName: tls-{{ template "resume.fullname" . }}
  rules:
  # Все запросы которые приходят на этот хост будут перенаправляться на этот сервис
  - host: {{ .Values.host }}
    http:
      paths:
        # Тип Prefix означает что все запросы которые начинаются на vasiliy.basov.world/... будут перенаправляться на наш сервис вместо ... может быть все что угодно
        - pathType: Prefix
          path: /
          backend:
            # Указываем имя сервиса и порт сервиса куда будет посылаться трафик с запросов которые будут приходить на хост vasiliy.basov.world
            service:
              name: {{ template "resume.fullname" . }}
              port: 
                number: {{ .Values.service.externalPort }}
