apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ template "resume.fullname" . }}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.email }}
    # Production server 
    server: {{ .Values.letsencryptserver }}
    privateKeySecretRef:
      # Secret resource that will be used to store the ACME account's private key.
      name: letsencrypt-prod-private-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          ingressClassName: {{ .Values.ingressClassName }}
