apiVersion: v1
kind: Service
metadata:
  namespace: test
  name: postgres-clusterip
spec:
  type: ClusterIP
  # selector для Deployment
  selector:
    components: postgres
  ports:
  # Порт указанный в deployment (ContainerPort)
  - port: 5432
    protocol: TCP
