apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: test
  name: postgres-pvc
spec:
  storageClassName: local-storage-postgres
  resources:
    requests:
      storage: 500Mi
  # Только один инстанс может туда писать и читать    
  accessModes:
    - ReadWriteOnce
