---
- name: Create /etc/nginx/sites-available directory
  ansible.builtin.file:
    path: /etc/nginx/sites-available
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create /etc/nginx/sites-enabled directory
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy conf file
  ansible.builtin.template:
    src: default.conf.j2
    dest: /etc/nginx/sites-available/{{ domain_name }}.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

- name: Copy conf file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

- name: Copy file for secure phpmyadmin connection
  ansible.builtin.template:
    src: pma_pass.j2
    dest: /etc/nginx/pma_pass
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

- name: Create symbolic link {{ domain_name }}.conf
  ansible.builtin.file:
    src: /etc/nginx//sites-available/{{ domain_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ domain_name }}.conf
    state: link
    force: yes
  notify: Restart Nginx

- name: Add nginx user to www-data group
  ansible.builtin.user:
    name: nginx
    groups: www-data
    append: yes

- name: Ensure Nginx service is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
