---
- name: Create /opt/wordpress directory
  file:
    path: /opt/wordpress
    state: directory

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/wordpress/docker-compose.yml

- name: Get infos on container wp_database
  community.docker.docker_container_info:
    name: wp_database
  register: result

- name: Does container exist?
  ansible.builtin.debug:
    msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

- name: Start MariaDB container
  command: docker-compose up -d
  args:
    chdir: /opt/wordpress
  when: not result.exists  


