apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  # На основании этого селектора происходит доступ к подам где прописан такой же label
  selector:
    app: http-server
  ports:
    - name: http
      protocol: TCP
      # Порт сервиса
      port: 80
      # Порт контейнера (вместо номера порта также можем использовать имя)
      # Тогда имя должно быть задано в секции spec.ports в Deployment
      targetPort: http
    - name: https
      protocol: TCP
      # Порт сервиса
      port: 80
      # Порт контейнера (вместо номера порта также можем использовать имя)
      # Тогда имя должно быть задано в секции spec.ports в Deployment
      targetPort: https
  # Default Type. Ip назначается в пределах кластера. Только внутренний.
  type: ClusterIP
