- name: create prometheus system group
  ansible.builtin.group:
    name: "{{ group }}"
    system: true
    state: present

- name: Create "{{ user }}" user
  become: true
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"
    createhome: false
    comment: "Prometheus server user"
    home: "{{ prometheus_db_dir }}"
    # ограничивает возможности взаимодействия с системой для пользователя через командную оболочку.
    shell: /bin/false

- name: download prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp

- name: unarchive prometheus
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp
    
- name: move prometheus to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/
    dest: "{{ prometheus_binary_install_dir }}"
    remote_src: true
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0774'

- name: Create {{ prometheus_config_dir }} directory for config
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0774'

- name: create rules.yml config
  ansible.builtin.template:
    src: rules.yml
    dest: "{{ prometheus_config_dir }}/rules.yml"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0774'
    validate: "{{ prometheus_binary_install_dir }}/promtool check rules %s"
  notify: Reload prometheus
  tags: prometheus_config

- name: create rules_alert.yml config
  ansible.builtin.template:
    src: rules_alert.yml
    dest: "{{ prometheus_config_dir }}/rules_alert.yml"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0774'
    validate: "{{ prometheus_binary_install_dir }}/promtool check rules %s"
  notify: Reload prometheus
  tags: prometheus_config

- name: Create {{ prometheus_config_dir }}/sd directory for service discovery
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}/sd"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0774'

- name: create node_exporter.yml config for service discovery from file
  ansible.builtin.template:
    src: node_exporter.yml
    dest: "{{ prometheus_config_dir }}/sd/node_exporter.yml"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0774'
  notify: Reload prometheus
  tags: prometheus_config

- name: create prometheus.yml config
  ansible.builtin.template:
    src: prometheus.yml
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0774'
    validate: "{{ prometheus_binary_install_dir }}/promtool check config %s"
  notify: Reload prometheus
  tags: prometheus_config

- name: Create "{{ prometheus_db_dir }}" directory for PromDB
  ansible.builtin.file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0755'

- name: create file with $option template
  ansible.builtin.template:
    src: prometheus
    dest: /etc/default/prometheus
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
  notify: Restart prometheus

- name: install unit file to systemd
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart prometheus

- name: configure systemd to use service
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: prometheus.service

- name: Ensure prometheus is running.
  ansible.builtin.uri:
    url: "http://127.0.0.1:9090/graph"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 5
  delay: 1
