apiVersion: v1
kind: Service
metadata:
  name: kuber-service
spec:
  # Это поле идентично тому которое есть в Deployment чтобы взаимодействовать с теми же pods
  selector:
    app: http-server
  ports:
    - protocol: TCP
      # Порт по которому будет отвечать сам сервис
      port: 80
      # Порт на контейнерах pods (containerPort) к которым подключаемся.
      targetPort: 80
  type: NodePort
